### ISSUE TITLE
No Fixing Occuring

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#177]
Just done a clean install and now the script isn't working for me.
![screenshot_2016-10-01_10-03-24](https://cloud.githubusercontent.com/assets/5920259/19013056/5eda28e8-87be-11e6-9d4d-3367da1a0ce3.png)
I don't know if it's relevant but the icon theme isn't being correctly detected either. I have ownCloud installed which is covered and should have been fixed, but there's also Rambox (an electron app) which isn't being fixed. I can open a new issue for that if you'd prefer?
![screenshot_2016-10-01_10-04-07](https://cloud.githubusercontent.com/assets/5920259/19013058/66f05d04-87be-11e6-800d-1217211bd8ab.png)

**Comment by bil-elmoussaoui** [comment]
You can always force the script to use an other icon theme than the one detected automatically! Just add --theme Numix (take a look at the readme for more info).
Can you open a new issue for Rambox? I will push a fix for it by this evening

**Comment by bil-elmoussaoui** [comment]
I just add Rambox support! You can either use the git version or wait few days until i release the 4.0 version :)

**Comment by Foggalong** [comment]
Awesome, I'll get some icons for Numix asap :)

**Comment by Foggalong** [comment]
@bil-elmoussaoui ownCloud isn't still being detected / fixed :confused:

**Comment by bil-elmoussaoui** [comment]
Can you check if this folder exists in your case ? https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/db.csv#L36 if not can you check if there's a folder/file that i can use to check if owncloud installed

**Comment by Foggalong** [comment]
I have `/usr/share/owncloud-client/` :+1:

**Comment by bil-elmoussaoui** [comment]
Pushed a new commit to fix that! can  you try the latest git version?

**Comment by Foggalong** [comment]
Nope, still not fixing for me :confused:

**Comment by bil-elmoussaoui** [comment]
@Foggalong add this to db.csv `OwnCloud, owncloud, /usr/share/owncloud-client/,` don't understand why it wasnt commited before..

**Comment by Foggalong** [comment]
@bil-elmoussaoui I'm having this issue again. I have both Rambox and ownCloud installed but neither are being fixed/reverted.

**Comment by bil-elmoussaoui** [comment]
Are you sure that u re using the latest git version of Hardcode-Tray? If you do how do you run the script ?

**Comment by Foggalong** [comment]
Yup, I recloned just to be sure it wasn't a problem with my local repo. I run it using this command: `sudo -E ./script.py --theme Numix`

**Comment by bil-elmoussaoui** [comment]
I will release a new version tonight!

**Comment by bil-elmoussaoui** [comment]
I updated Hardcode-Tray to 3.2, can you try if everything works great again?

**Comment by Foggalong** [comment]
@bil-elmoussaoui Nope still not working. Can you reopen this issue?

**Comment by bil-elmoussaoui** [comment]
I've added an other OwnCloud path to the database file, can you clone the repo and try again?

**Comment by Foggalong** [comment]
It now says it's being fixed, but doesn't actually fix. Also Rambox it doesn't say it's fixing either, but not sure if that's expected?

**Comment by bil-elmoussaoui** [comment]
@Foggalong Do you have the patched version of sni-qt installed? and for Rambox, do you have the latest version of Numix base with Rambox icons? Also it's might due to the installation path of Rambox. On Arch, it's installed on /opt/rambox/. Can you confirm it's installed there in your case too? 
+ I've updated the db.csv file, can you clone and try again?

**Comment by Foggalong** [comment]
For ownCloud, the problem was that I don't have the patched sni-qt installed. The PPA doesn't have Yakkety builds though so I also can't :/

For Rambox, the installation location for Ubuntu is `/opt/Rambox`

**Comment by bil-elmoussaoui** [comment]
Should be fixed for Rambox, just update db.csv file with the latest git version.
You can build it from source, it shouldn't be that complicated, just follow the documentation https://github.com/bil-elmoussaoui/Hardcode-Tray/wiki/How-to-build-sni-qt

**Comment by Foggalong** [comment]
@bil-elmoussaoui I'm more than happy to build from source, but it's not an especially user friendly method. Even as building from source goes it's more complicated than normal.

**Comment by bil-elmoussaoui** [comment]
Alright! Hope the PPA will be updated soon, otherwise i will have to create a new PPA myself.. Does Rambox issue still occuring?

**Comment by Foggalong** [comment]
Yeah, Rambox is now working for me which is brilliant :+1:

**Comment by Foggalong** [comment]
Interesting thing for Rambox: it also changes the Rambox icon within the app to the tray icon. Guessing that there's nothing that can be done about this so no worries :+1:
![screenshot_2016-10-31_15-36-36](https://cloud.githubusercontent.com/assets/5920259/19860230/e147fea8-9f7f-11e6-8a16-f0e174e7e975.png)

ownCloud though unfortunately still not fixed, even with the patched version of SNI Qt installed (inc. 32 bit version).

**Comment by bil-elmoussaoui** [comment]
You can report that to Rambox dev so they can change the icon they're using there :) I only change the Tray icon.. 
I can't do anything about it, the issue is related to sni-qt or the way you build it! Hope that elementaryPlus guys will update their PPA soon! 
This can be closed now? :)

**Comment by Foggalong** [comment]
I mean, this issue isn't really fixed. I built sni-qt using the instructions here so at the very least a disclaimer needs to be added saying that it won't work in the latest version of Ubuntu :crying:

Even disregarding that, there's the problem that the script is telling the user than stuff is being fixed when it isn't. I'm not sure whether that's something that can be detected though?

**Comment by bil-elmoussaoui** [comment]
I don't think there's a way to detect if the patched version of sni-qt is installed using Python, the script is telling to the user the sni-qt application were fixed which means that the icons were copied correctly to the right directory. And as mentioned on the README the user must have the patched version of sni-qt installed. And i wasn't able to build sni-qt correctly neither so :(

**Comment by Foggalong** [comment]
That's fair enough. Probably go with the disclaimer then that it doesn't work with Yakkety yet. I've filed an issue upsteam so hopefully it will be updated soon.

**Comment by bil-elmoussaoui** [comment]
I'm going to close this, as i don't think that i will be able to maintain a PPA at this moment! if i find any better way to compile the patched version, i will do it!
