### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by Sadi58** [bil-elmoussaoui/Hardcode-Tray#190]
On Ubuntu 16.10 64-bit, I get the following terminal output:

```
Traceback (most recent call last):
  File "/opt/Hardcode-Tray/script.py", line 75, in <module>
    "svgtopng", "%s/database/scripts/svgtopng.py" % absolute_path)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/Hardcode-Tray//database/scripts/svgtopng.py", line 11, in <module>
    require_version('Rsvg', '2.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Rsvg not available
```

**Comment by bil-elmoussaoui** [comment]
Please upgrade to the latest version, you seem to be using 3.3, this issue was fixed here #188

**Comment by Sadi58** [comment]
Thanks, but I've just cloned the git repository; maybe this is because I don't have Rsvg installed - is it python-rsvg?

**Comment by bil-elmoussaoui** [comment]
You don't have to clone the git repo, just run hardcode-tray --update!  this will install the latest stable version. I don't know the package name on Ubuntu, if you ever figure out, please open a PR and add it to the list of dependecies ! the package is used to resize svg icons in order to add HiDPI support

**Comment by Sadi58** [comment]
I used this command (`cd /tmp && wget -O - https://raw.githubusercontent.com/bil-elmoussaoui/Hardcode-Tray/master/install.sh | bash`) to download and install the latest version, but I still get the same error message.
I have **librsvg2-2** [_SAX-based renderer library for SVG files (runtime)_] and **librsvg2-common** [_SAX-based renderer library for SVG files (extra runtime)_] packages (**version 2.40.16-1**) installed.
Also installed packages **librsvg2-bin** and **python-rsvg**, but no change.
I don't know python, but could `require_version('Rsvg', '2.0')` mean incompatibility with version 2.40?

**Comment by bil-elmoussaoui** [comment]
What's the output of hardcode-tray --version ?

**Comment by Sadi58** [comment]
3.4

**Comment by bil-elmoussaoui** [comment]
Do you have Inkscape installed ?

**Comment by Sadi58** [comment]
Yes, I have it in working condition, but not the `python3-cairosvg` package, which I guess is not required if `inkscape` is already installed.

**Comment by bil-elmoussaoui** [comment]
Fixed the issue on git version ;) i will create a new release once i've fixed more stuff!

**Comment by bil-elmoussaoui** [comment]
Fixed the issue on git version ;) i will create a new release once i've fixed more stuff!

**Comment by Sadi58** [comment]
Thanks a lot; working great now!
It fixed that hardcoded tray icon issue even for the new skypeforlinux (alpha/beta) which no longer requires a patched version of `sni-qt`!
BTW I have a lot of git repositories which are synched automatically at startup, that's why I also included **Harcode-Tray** among them, and simply symlinked its local directory to `/opt` and then symlinked `/optHarcode-Tray/hardcode-tray` to `/usr/bin` -- this installation method also works with no problem at all.

**Comment by bil-elmoussaoui** [comment]
@Sadi58 Yeah we do support almost all electron applications, here's a list of supported applications https://github.com/bil-elmoussaoui/Hardcode-Tray/wiki/Supported-applications

**Comment by Sadi58** [comment]
Thanks a million for this total solution!
I've just said goodbye to https://github.com/pwittchen/fix-skype-icon ;-)
